#副手40 头盔39 胸甲38 护腿37 靴子36
#┌—————┬———————————┐
#│ 39  │           │        ← 39 头盔
#├—————┤           │
#│ 38  │           │        ← 38 胸甲
#├—————┤           │
#│ 37  │           │        ← 37 护腿
#├—————┤           ├—————┐
#│ 36  │           │ 40  │  ← 36 靴子  ← 40 副手
#├─——──┼──——─┬──——─┼──——─┼──——─┬─——──┬──——─┬—————┬—————┐
#│ 27  │ 28  │ 29  │ 30  │ 31  │ 32  │ 33  │ 34  │ 35  │
#├─——──┼─——──┼──——─┼─——──┼──——─┼——───┼─——──┼──——─┼——───┤
#│ 18  │ 19  │ 20  │ 21  │ 22  │ 23  │ 24  │ 25  │ 26  │         ← 主物品栏（9-35）
#├─——──┼─——──┼──——─┼─——──┼──——─┼——───┼─——──┼──——─┼——───┤
#│ 9   │ 10  │ 11  │ 12  │ 13  │ 14  │ 15  │ 16  │ 17  │
#├─——──┼─——──┼──——─┼─——──┼──——─┼——───┼─——──┼──——─┼——───┤
#│ 0   │ 1   │ 2   │ 3   │ 4   │ 5   │ 6   │ 7   │ 8   │         ← 快捷栏（0-8）
#└──——─┴─——──┴─——──┴─——──┴─——──┴─——──┴──——─┴─——──┴─——──┘
Inventory:
  0: # 键名无特殊要求，建议使用常见字符，所有配置中不能有重复键名
    slot: 0 # 槽位，见配置文件头图示
    material: "STICK" #物品材质，使用枚举名
    display-name: "§c轻杆"
    nbt: #nbt写在这里将添加在物品上
      Enchantments:
        "unbreaking": 0 #占位作用
      HideFlags: 3

  1:
    slot: 1
    material: "STICK"
    display-name: "§c中杆"
    nbt:
      Enchantments:
        "knockback": 2
        "unbreaking": 0
      HideFlags: 3

  2:
    slot: 2
    material: "STICK"
    display-name: "§c重杆"
    nbt:
      Enchantments:
        "knockback": 4
        "unbreaking": 0
      HideFlags: 3

# 大厅世界名称
lobby-world: "world"

# 其他配置...