name: TableBall
version: 1.0.0
main: org.tableBall.TableBall
api-version: 1.20
depend: [Multiverse-Core]

commands:
  inviteplayer:
    description: 邀请玩家到指定世界开始游戏
    aliases: [ip]
    usage: /inviteplayer <玩家> <世界> <类型> <对局数>
    permission: tableball.invite
  leave:
    description: 离开当前游戏并返回大厅
    usage: /leave
  acceptinvite:
    description: 接受TableBall游戏邀请
    usage: /acceptinvite
    permission: tableball.invite
  editmode:
    description: 切换编辑模式
    usage: /<command> <enable/disable/info>
    permission: tableball.editmode
  spectategame:
    description: 观战
    usage: /spectategame

permissions:
  tableball.invite:
    description: 允许使用/inviteplayer命令
    default: true
  tableball.leave:
    description: 允许使用/leave命令
    default: true
  tableball.admin:
    description: 给予所有TableBall权限
    default: op
    children:
      tableball.invite: true
      tableball.leave: true
